# Streamlit Secrets für SharePoint
[sharepoint]
site_url = "https://medealis.sharepoint.com"
client_id = "178e93f1-7488-4e10-9e69-1a95055bd2f5"
client_secret = "2Fa8Q~u3pbNyN0FwE1bgCkCaEfSgmIuDOrlPwaM1"
tenant_id = "9422968d-1c58-4592-81e6-04bc95a22130"

[storage]
use_sharepoint = true
